<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Riesgos</name>
   <tag></tag>
   <elementGuidId>0ea575fc-d6f4-4677-a8ee-f01e1d31bfe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='datosRiesgoContent']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8e0e95f-5929-4f7a-a919-3e76da845391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-8</value>
      <webElementGuid>f2b8fdaa-8230-4daa-b4ea-b3eb271ee0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Riesgos
  </value>
      <webElementGuid>ea02a502-47d3-4cf5-a474-f81327d777bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datosRiesgoContent&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-8&quot;]</value>
      <webElementGuid>b5ad8f6d-f73c-4546-ac66-a8db1adf1abb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datosRiesgoContent']/div/div</value>
      <webElementGuid>f1c36dc0-9c91-4be7-80ee-64d56caad799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado: Incompleta'])[1]/following::div[3]</value>
      <webElementGuid>094f4a58-364c-4607-8518-83194ef62995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasas y franquicias automáticas'])[1]/preceding::div[1]</value>
      <webElementGuid>4764fa07-d5fc-47ac-b3a7-3c6992f0feb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>679f178f-8258-40bf-b4a5-c6cead2e9f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
    Riesgos
  ' or . = '
    Riesgos
  ')]</value>
      <webElementGuid>186cb734-0a4c-4ac2-bdd5-d7a52951ebc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
