<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_This page requires frames in order t_99ba60</name>
   <tag></tag>
   <elementGuidId>38ae68dc-77da-4499-a5e8-772dafe08d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.k-content-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalWindow']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>84b7cf1c-493e-48cd-8255-a80f1cb1cf22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0891f8f1-de51-4ea1-9ff5-9ee860b87001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nuevo viaje</value>
      <webElementGuid>9dcbe33c-b282-44ed-a3a8-c5d0040d712a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-content-frame</value>
      <webElementGuid>cd18c2f9-d08f-4de1-baea-dd63dcf662e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/AdInsurance/Emision/Gestion/DeclaracionViajeTransporte/Create?ramoId=326&amp;poliza=000000000863&amp;abmModal=true</value>
      <webElementGuid>dc4d7397-ee9a-461a-87af-7f94aee24b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This page requires frames in order to show content</value>
      <webElementGuid>9457a76a-68a0-4494-8856-a33670a934a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalWindow&quot;)/iframe[@class=&quot;k-content-frame&quot;]</value>
      <webElementGuid>d326acc6-063f-4488-8c24-792e65d45274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>16c79f93-b11d-468c-960c-72306186743d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9b44e3cc-de9f-457b-a1c8-90d96ac0f936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nuevo viaje</value>
      <webElementGuid>ce67f545-d27d-4fc2-9382-69997ed54bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-content-frame</value>
      <webElementGuid>04c21607-09f1-4f1a-a7f7-ecde74f0131b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/AdInsurance/Emision/Gestion/DeclaracionViajeTransporte/Create?ramoId=326&amp;poliza=000000000863&amp;abmModal=true</value>
      <webElementGuid>fcece2f7-6851-4702-90bb-f8a8b1cbba08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This page requires frames in order to show content</value>
      <webElementGuid>1f66bbe6-f8e8-49f3-a846-9bce37796eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalWindow&quot;)/iframe[@class=&quot;k-content-frame&quot;]</value>
      <webElementGuid>8336cc39-0fb3-4b76-adf2-4b716b248e2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalWindow']/iframe</value>
      <webElementGuid>a728b68d-4d1d-42dd-aba9-de637ce0b981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuevo viaje'])[1]/following::iframe[1]</value>
      <webElementGuid>e487116b-bbb6-48b2-81fa-bdfd4b9bb77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No se encontraron datos.'])[9]/following::iframe[1]</value>
      <webElementGuid>603779ae-aa95-4ed5-85dd-212fa852203a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This page requires frames in order to show content']/parent::*</value>
      <webElementGuid>00f480b0-9d41-4696-9400-cc1b3e4ebe96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>104e39eb-b8d4-4edc-842f-b41bae27f6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Nuevo viaje' and @src = '/AdInsurance/Emision/Gestion/DeclaracionViajeTransporte/Create?ramoId=326&amp;poliza=000000000863&amp;abmModal=true' and (text() = 'This page requires frames in order to show content' or . = 'This page requires frames in order to show content')]</value>
      <webElementGuid>899d6a79-3674-4dfe-9924-f10cb0b36b86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
