<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Localidad_LocalidadId.XmlValue_input</name>
   <tag></tag>
   <elementGuidId>3ebf153a-14d3-4934-acb2-d8600465e656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='LocalidadId.XmlValue_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;LocalidadId.XmlValue_input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d70cd62-f821-4bb4-8d86-cfb21fa2b3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LocalidadId.XmlValue_input</value>
      <webElementGuid>85194920-4441-4bac-a8ee-273677a12a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>8358a0bc-9678-4d61-91b8-54a1471b6fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d60c500-8a77-4ff1-b5f2-674e3a7af6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a98172d8-d20f-4f41-a3c5-85ef9f843f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>4b7ff047-d595-43f7-bfcb-31b36d96d4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>96631f08-1f10-4351-aa33-efdec9f82a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese al menos 3 caracteres para la búsqueda...</value>
      <webElementGuid>258ae8c5-9a6f-4626-a44b-e301fd5ded08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8c98dd44-489d-4b3c-b52e-04593df4feb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2c2a2b64-4b3a-4ab3-a8c5-99d77a6c2f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d022ccc8-560c-4e4d-b74c-bb4c7bbc5a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>08f6baa5-36c6-472a-b7a9-1d7d18080704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>LocalidadId_XmlValue_listbox</value>
      <webElementGuid>ad527fa5-15e3-48bb-8d04-c5d549bb1fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>LocalidadId_XmlValue_listbox</value>
      <webElementGuid>0a67ecf5-fcac-4417-a226-fcb920bb5844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-busy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b5d40544-7806-4701-a382-f1541438390b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>d9e30fb2-fc11-48a1-b688-7fe4f1ae5b32</value>
      <webElementGuid>7d34b48e-44ec-4a2d-bf47-3489d09eaed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divLocalidadId&quot;)/span[@class=&quot;k-widget k-combobox k-combobox-clearable&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-focused k-state-hover&quot;]/input[@class=&quot;k-input&quot;]</value>
      <webElementGuid>f5179914-ba18-435b-a658-7f4108d4af5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='LocalidadId.XmlValue_input']</value>
      <webElementGuid>eec186d5-0693-4891-8701-018c99a4104b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divLocalidadId']/span/span/input</value>
      <webElementGuid>49d8d6b0-0ae4-4a54-8da1-0dd782f65549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/span/span/input</value>
      <webElementGuid>70200f90-7d24-4d10-997e-5b8173142e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'LocalidadId.XmlValue_input' and @type = 'text' and @placeholder = 'Ingrese al menos 3 caracteres para la búsqueda...']</value>
      <webElementGuid>9b1d1778-fe50-44e8-a25c-9284a59dc47e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
