<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_localidad</name>
   <tag></tag>
   <elementGuidId>69120c62-69ae-4510-95b5-d316f0621286</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@id = 'lblLocalidadId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bff6e0d0-9557-4a48-8fc2-db5b4f5fcd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lblLocalidadId</value>
      <webElementGuid>c334550f-966e-4519-bd4a-a14640b529c7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
