<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Monto estimado_k-numeric-wrap k-state-_37bfe5</name>
   <tag></tag>
   <elementGuidId>21339117-1b16-4a77-a1a9-2878e9f0b9a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalBody']/div/div/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.k-numeric-wrap.k-state-default.k-expand-padding.k-state-hover.k-state-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>88f9c811-ba07-497e-b0df-94139c9c8d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-numeric-wrap k-state-default k-expand-padding k-state-hover k-state-focused</value>
      <webElementGuid>6d1eb550-a096-4fb5-861a-a09ea8a1a91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalDetalleRiesgoTransporte&quot;)/div[@class=&quot;modal-dialog modal-sm&quot;]/div[@class=&quot;modal-content&quot;]/div[@id=&quot;modalBody&quot;]/div[@class=&quot;display-table&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-3&quot;]/span[@class=&quot;k-widget k-numerictextbox&quot;]/span[@class=&quot;k-numeric-wrap k-state-default k-expand-padding k-state-hover k-state-focused&quot;]</value>
      <webElementGuid>24e21435-8db5-4aa8-8afb-d0cd451ccf98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalBody']/div/div/div/span/span</value>
      <webElementGuid>317fb1e4-9de0-471e-b25c-8a64f7244cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto estimado'])[2]/following::span[2]</value>
      <webElementGuid>00576315-54a4-4e94-81a4-58e3b5ca8378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalle de riesgo: Transito aéreo (726)'])[1]/following::span[2]</value>
      <webElementGuid>814352c4-0c80-4830-ac60-1e02d7c31045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suma asegurada'])[2]/preceding::span[7]</value>
      <webElementGuid>bed4dab6-b974-47ca-b7e4-60439f693421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[7]/preceding::span[7]</value>
      <webElementGuid>d0f5da84-0451-44f4-b109-178508130ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/span</value>
      <webElementGuid>43caf8de-c5c0-43f9-b8a7-c8f6949a8bce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
