<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_45.000,00</name>
   <tag></tag>
   <elementGuidId>7dbb3cf9-c8ce-406f-9ab2-bd2ebb8fe3ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spanSumaAsegurada']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#spanSumaAsegurada</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7cf94cf4-64b4-42e9-bd12-efd9000a9a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spanSumaAsegurada</value>
      <webElementGuid>faa9109b-2bd8-4635-bbb6-803e9a9b5d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>45.000,00</value>
      <webElementGuid>69be372c-bd54-46f4-9605-911dea1b14bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanSumaAsegurada&quot;)</value>
      <webElementGuid>32c42292-05c8-49e6-94a7-a0acbf3d69a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Alta de Endoso - Transporte de Mercaderas/iframe_This page requires frames in order t_99ba60</value>
      <webElementGuid>2d81ad47-6798-408e-a470-2c8b847a82cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='spanSumaAsegurada']</value>
      <webElementGuid>f6e0acab-9f7a-4760-98af-6678e9b64846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grdRiesgoTransporte']/table/tfoot/tr/td[5]/span</value>
      <webElementGuid>e9660c35-75cd-4657-b19c-91e4662fc75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/following::span[1]</value>
      <webElementGuid>3d40e65e-2b68-4aee-bf26-a63cbb839e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destinos'])[1]/following::span[1]</value>
      <webElementGuid>93e91681-5185-43de-b904-38873b44d7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transito aéreo'])[1]/preceding::span[2]</value>
      <webElementGuid>ea5b0a8a-444a-4a33-88bf-adb29cb7da81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sí'])[1]/preceding::span[3]</value>
      <webElementGuid>dd8cd47d-94bd-4aae-8a76-70d91956268a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='45.000,00']/parent::*</value>
      <webElementGuid>da1beea0-d92d-4ade-8ce7-8193ac70f3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/span</value>
      <webElementGuid>0dff39e3-40cf-4c1b-be2c-8424eddb7b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'spanSumaAsegurada' and (text() = '45.000,00' or . = '45.000,00')]</value>
      <webElementGuid>bbf1766c-0eeb-4e09-ad31-d91fa2445947</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
