<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_130.000,00</name>
   <tag></tag>
   <elementGuidId>27fa2774-5b5e-4bc2-b79d-5b33a0345efa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='grdRiesgoTransporte_active_cell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#grdRiesgoTransporte_active_cell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5952b62c-5613-4a12-b890-db396ff26eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable k-state-focused</value>
      <webElementGuid>0fb98f29-61d3-47c0-832c-570b7ebacfba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>b8cbc008-cd8b-4596-b5e0-b2384eea975a</value>
      <webElementGuid>4bffbbe9-8629-457d-878c-6bcd380fbb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>cf4941a5-7cee-4855-8c01-d460bf41a498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grdRiesgoTransporte_active_cell</value>
      <webElementGuid>5c6da678-d608-4d80-9f57-ab2dba38b1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>130.000,00</value>
      <webElementGuid>4c850379-5654-4a07-b107-cc2fd42c62aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdRiesgoTransporte_active_cell&quot;)</value>
      <webElementGuid>f8054bdd-1e60-492d-aaec-55c83bc9e992</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='grdRiesgoTransporte_active_cell']</value>
      <webElementGuid>ea0196aa-d582-4268-9835-a01ce06c4b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grdRiesgoTransporte']/table/tbody/tr/td[4]</value>
      <webElementGuid>99de250d-0be4-4f18-a14a-6c7ccf60c64b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transito aéreo'])[1]/following::td[1]</value>
      <webElementGuid>88e9c5e4-38f6-4b35-ad75-84aa449b6465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/following::td[15]</value>
      <webElementGuid>7451be1f-6b7b-451e-bc17-f0336cdb8291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sí'])[3]/preceding::td[4]</value>
      <webElementGuid>15655471-6fb7-434b-a3b9-c41d575dd8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sí'])[4]/preceding::td[5]</value>
      <webElementGuid>f233b15a-8b33-4daa-a027-7b0dfcf46a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='130.000,00']/parent::*</value>
      <webElementGuid>f4f36fb3-6c34-408a-9fcc-07e48694695b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td[4]</value>
      <webElementGuid>8535dc8c-e433-4e13-b42f-c9c874dedcd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'grdRiesgoTransporte_active_cell' and (text() = '130.000,00' or . = '130.000,00')]</value>
      <webElementGuid>308b33bc-26ef-4c32-bc9f-d4caec50ef18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
