<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Transito areo_grdRiesgoTransporte_active_cell</name>
   <tag></tag>
   <elementGuidId>99430774-a034-44ad-8254-5257aaa25019</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='grdRiesgoTransporte_active_cell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#grdRiesgoTransporte_active_cell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a7e5cd90-36cc-4211-b1f7-34243cb5efde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable k-state-focused</value>
      <webElementGuid>3ee88b43-4e6f-4edc-b8be-06d0e8eab758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>df44c116-01fc-44f4-931e-b6a34f1dd79b</value>
      <webElementGuid>21b17cb1-c16b-452d-8e1e-a68d4204e082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>5b40008f-1dc5-481f-8995-4f71bc420355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grdRiesgoTransporte_active_cell</value>
      <webElementGuid>a9daade9-f5bc-4b59-bdd3-b0366234602e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdRiesgoTransporte_active_cell&quot;)</value>
      <webElementGuid>c41dfba3-6786-444c-bd9c-0dff0334961d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Alta de Endoso - Transporte de Mercaderas/iframe_This page requires frames in order t_99ba60</value>
      <webElementGuid>591f1e47-ff05-41fe-be60-7da1d70a8d33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='grdRiesgoTransporte_active_cell']</value>
      <webElementGuid>2a26c3d3-326e-4ef2-910f-58f648f50228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grdRiesgoTransporte']/table/tbody/tr/td[5]</value>
      <webElementGuid>b7a92d6d-aa9b-4192-a87f-02b1baf1f00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td[5]</value>
      <webElementGuid>a26b8678-d59a-494f-91fd-16ac93fb523a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'grdRiesgoTransporte_active_cell']</value>
      <webElementGuid>a3f2b13b-b5d6-4816-84e4-ec77939e4181</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
