<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_divCondicionIva</name>
   <tag></tag>
   <elementGuidId>394f1d66-c06f-4947-9e8e-a3ad17aafc76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@id, 'divCondicionIvaId')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>458a3e3a-4033-4009-a20c-7a89a4f7f603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>divCondicionIvaId</value>
      <webElementGuid>bf4df7bd-488b-4e0e-8b5f-f2953d209847</webElementGuid>
   </webElementProperties>
</WebElementEntity>
