<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_EstadoPoliza4</name>
   <tag></tag>
   <elementGuidId>d3aa3d83-3d02-4991-b903-30d32bc62daa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;grdConsultaMovimiento&quot;]/table/tbody/tr[4]/td[@id=&quot;EstadoPolizaDescripcion&quot;]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
