<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_moneda</name>
   <tag></tag>
   <elementGuidId>d81e0c36-7403-46ec-84e6-47af77ec51f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'MonedaId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4799a8e1-f6b9-47d8-86c8-642858e30ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MonedaId</value>
      <webElementGuid>c4c6f09c-bc5e-4e11-8a68-3417d0bc3e3e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
