<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_productorPrincipal0</name>
   <tag></tag>
   <elementGuidId>ac6a0b09-6f48-4289-9e5a-2f3c1e13bedc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'ProductorPrincipalId_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60c3cc08-f1dd-4b47-b7e9-c60c203739b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductorPrincipalId_input</value>
      <webElementGuid>14503c46-8d77-4c07-b84f-402ba81b2cf4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
