<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_productorPrincipal1</name>
   <tag></tag>
   <elementGuidId>1ff6c1b5-4550-41b9-87b3-141c09484c34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'ProductorPrincipalId']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ProductorPrincipalId_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8f29ef0-2aae-40dc-86fa-edd9ad25de01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductorPrincipalId</value>
      <webElementGuid>cafc32e9-68ca-481b-8221-4e23d6c6cdc5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
