<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bitcora_lnkNuevaBitacora</name>
   <tag></tag>
   <elementGuidId>a6181fb9-346d-4952-a7ee-c5fbe3f0a03f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lnkNuevaBitacora</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lnkNuevaBitacora']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e0896644-831f-4f6a-a15a-d74c217a0400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lnkNuevaBitacora</value>
      <webElementGuid>f8167121-716f-490e-b9ac-94e6787be42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Agregar observación</value>
      <webElementGuid>de2d1e7b-e055-4992-a042-0ee16040f296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>67f3b60c-11fb-4b06-962b-7ad21326bfe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AgregarBitacora();</value>
      <webElementGuid>938b74cb-b44c-4700-8482-82fb3b362c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lnkNuevaBitacora&quot;)</value>
      <webElementGuid>79821eb2-c607-4a89-b47c-b2c9a01585de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lnkNuevaBitacora']</value>
      <webElementGuid>bfd001ea-e5c8-4531-a9a6-9de449318406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divNuevaBitacora']/a</value>
      <webElementGuid>85f2a121-0eb2-4f82-bf1a-a55053511274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local [1]'])[1]/following::a[1]</value>
      <webElementGuid>c7a4b27f-bdee-46b9-b737-27b5077499db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Observaciones'])[1]/preceding::a[3]</value>
      <webElementGuid>eeb37cf4-6c61-492f-b91b-f966d5b2f280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No hay registros'])[1]/preceding::a[8]</value>
      <webElementGuid>a9856895-4a83-4556-a7ee-654fb15e2cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/a</value>
      <webElementGuid>c87b4750-aae8-4397-93ff-e625ea5e1b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lnkNuevaBitacora' and @title = 'Agregar observación']</value>
      <webElementGuid>5e5bac69-a860-4add-915d-41235b6dcf2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
