<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Bitcora_txtNuevaBitacora</name>
   <tag></tag>
   <elementGuidId>0fa7247c-6884-4019-a1e4-fbe09f1fefb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtNuevaBitacora']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtNuevaBitacora</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>915b2bf1-58b3-46fe-8eb5-bec35b30049a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-textbox multiline</value>
      <webElementGuid>898f9480-e307-464c-85a5-0afd7428003f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNuevaBitacora</value>
      <webElementGuid>c92d32b7-2683-4ce3-a1c0-8a5c7b67fbd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>4a7f55c7-845a-4b6e-b644-0d4f0b117614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtNuevaBitacora</value>
      <webElementGuid>930030a8-b602-402b-8b67-5d44299ac7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNuevaBitacora&quot;)</value>
      <webElementGuid>a0caee31-39af-4390-87ad-ec614ba1b711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtNuevaBitacora']</value>
      <webElementGuid>924fb852-4bbe-4aca-9fab-eb78d9fbf41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divNuevaBitacora']/textarea</value>
      <webElementGuid>03eb0679-458e-4b1f-8647-baebdc15cc32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>54c1ec63-5cbd-4398-beee-313f6588bf24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'txtNuevaBitacora' and @name = 'txtNuevaBitacora']</value>
      <webElementGuid>cc6d33ac-3c89-474c-804a-5f53cd364c49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
