<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CUIT_CUIL</name>
   <tag></tag>
   <elementGuidId>39d607ab-ac71-4ab4-b9d5-13032a9ac167</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'cuit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24423be9-ed98-4ffa-83da-bbc85bc2a96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cuit</value>
      <webElementGuid>af7e29b3-a20e-48e9-95c7-a6ff901d0a53</webElementGuid>
   </webElementProperties>
</WebElementEntity>
