<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Productor principal_k-icon k-i-x</name>
   <tag></tag>
   <elementGuidId>c5f7a19b-b501-4a77-a8f9-9f9571f60ece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-icon.k-i-x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='filtrosBasicosContainer']/div[11]/div/span/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a0360a3f-22a1-49b0-8b9c-ff969f485c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-x</value>
      <webElementGuid>e42efdd2-3004-4bca-9f0b-8c769fde545f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filtrosBasicosContainer&quot;)/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;form-group form-group-filter&quot;]/span[@class=&quot;k-widget k-combobox k-combobox-clearable&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover&quot;]/span[@class=&quot;k-clear-value&quot;]/span[@class=&quot;k-icon k-i-x&quot;]</value>
      <webElementGuid>6c69097b-7fde-4827-8f5d-9fe95f152939</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filtrosBasicosContainer']/div[11]/div/span/span/span/span</value>
      <webElementGuid>d685199f-54e9-44bf-be1f-009444498ff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/span/span/span/span</value>
      <webElementGuid>a2c6dec1-2fb1-49ca-8c70-fd1e539fe353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
