<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Avanzados</name>
   <tag></tag>
   <elementGuidId>0f83e913-4e85-4493-9d21-69c8fcc0bcac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lnkPanelFiltrosAvanzados > span.hidden-xs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lnkPanelFiltrosAvanzados']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a112e41d-3422-4589-bfd7-a021efedbe88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden-xs</value>
      <webElementGuid>54bece2d-0430-4153-a812-e10189f3c44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Avanzados</value>
      <webElementGuid>c87e34b1-1393-4c1d-acda-13a930c01052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lnkPanelFiltrosAvanzados&quot;)/span[@class=&quot;hidden-xs&quot;]</value>
      <webElementGuid>cc41f8f0-0c5b-4a07-a03b-81c197ffd301</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='lnkPanelFiltrosAvanzados']/span</value>
      <webElementGuid>9ca6b276-c9c4-411d-86b9-a5bcc42f7cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refrescar'])[2]/following::span[2]</value>
      <webElementGuid>1f720728-9096-40c6-b5e6-d41397b114e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuevo'])[1]/preceding::span[2]</value>
      <webElementGuid>3c762a09-b653-4162-9b8d-d63858250ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/span</value>
      <webElementGuid>993d8e22-1f9e-4bfe-af17-b60094482167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Avanzados' or . = ' Avanzados')]</value>
      <webElementGuid>631a5b20-1de2-46ba-88c1-48f9427019d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
