<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_TipoEndosoDescripcion_2</name>
   <tag></tag>
   <elementGuidId>e5822391-8342-4441-8507-66f9f53cefb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//td[@id='TipoEndosoDescripcion'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr > #CotizacionId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>065f84eb-0ea5-4c7d-80bf-9b2ae3994151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CotizacionId</value>
      <webElementGuid>769da545-b942-4cdc-a4db-a9c6fb310b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>c7216467-a042-4112-9028-6c764f72f9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>106560</value>
      <webElementGuid>bfcfa151-9f01-42f3-9515-fc19e77ed51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdConsultaMovimiento&quot;)/table[1]/tbody[1]/tr[1]/td[@id=&quot;CotizacionId&quot;]</value>
      <webElementGuid>f19ec981-1487-4f0d-afe5-216ca82ad872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='CotizacionId']</value>
      <webElementGuid>cc1dac9f-9b12-44af-a65c-b803e1e5a605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grdConsultaMovimiento']/table/tbody/tr/td[2]</value>
      <webElementGuid>ce049287-2ae8-488e-8574-25b298c3eaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo endoso'])[3]/following::td[2]</value>
      <webElementGuid>516984a1-18e6-4207-baed-f4f30d5611fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subramo'])[3]/following::td[2]</value>
      <webElementGuid>f95b23fe-91d1-4bfd-a8d6-0074bd0dcbaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autos'])[1]/preceding::td[1]</value>
      <webElementGuid>9dead086-7f0c-4400-9729-3f5a84ce8bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesos'])[1]/preceding::td[4]</value>
      <webElementGuid>be961825-7b21-45e4-8e6a-4f3f8652caa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>da1fc63d-8f83-4444-a6a4-7d1415d53279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
