<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_VigenciaContratoDescripcion_3</name>
   <tag></tag>
   <elementGuidId>7e3d64cb-9aab-42c7-96df-5ae9ddc082ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//td[@id='VigenciaDescripcion'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0b1f65d2-2551-4ebb-8492-d16b4acb6e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NumeroPropuesta</value>
      <webElementGuid>7533c280-ae2e-4176-a30d-d1ab0d90f8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>0d81c6eb-5800-4000-bcda-9ff8442dd71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdConsultaMovimiento&quot;)/table[1]/tbody[1]/tr[3]/td[@id=&quot;NumeroPropuesta&quot;]</value>
      <webElementGuid>712ab58f-9915-4899-a363-17bdc85f6df0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//td[@id='NumeroPropuesta'])[3]</value>
      <webElementGuid>791bb157-6b36-4fc9-ba2c-e03ad3078dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grdConsultaMovimiento']/table/tbody/tr[3]/td[28]</value>
      <webElementGuid>ba95405d-a3d9-4609-9546-b9a82f92acf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Póliza Nueva'])[2]/following::td[10]</value>
      <webElementGuid>6c6bf033-9e9f-4f42-b84a-9370df87e554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual'])[2]/following::td[12]</value>
      <webElementGuid>f23526df-ef39-48c2-bb0e-29aaa9f93573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHAVEZ, PAULA'])[3]/preceding::td[9]</value>
      <webElementGuid>852a03ac-4609-4d3b-85f7-bdbd5e2d8683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[28]</value>
      <webElementGuid>f21fe464-0ef3-45ff-92f3-2f6d72ceada0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
