<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_montoEstimadoTansitoAereo2</name>
   <tag></tag>
   <elementGuidId>daedd820-73cb-43e5-a9f3-93a469257612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'MontoEstimado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f9ccf68-5f3d-43b1-a6eb-e997cfbc3d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MontoEstimado</value>
      <webElementGuid>2ac9f38c-0085-4dec-a087-9cf6461424d5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
