<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_montoEstimadoTansitoAereo1</name>
   <tag></tag>
   <elementGuidId>76415699-d5c8-487a-89a8-cdd2f2f3a650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id=&quot;grdRiesgoTransporte_active_cell&quot;]/span[1]/span/input[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
