<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkboxEquipoSuscriptoresCaucion</name>
   <tag></tag>
   <elementGuidId>bcf1ddc2-70d7-4b6a-8317-3d75591ec1f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[2]/div[8]/section/div/div[5]/div[1]/div/div[2]/div/div/ul/li[9]/div/span[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
