<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_This page requires frames in order t_99ba60</name>
   <tag></tag>
   <elementGuidId>630871c3-b0df-47d0-83fc-72d2e3562528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.k-content-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalWindow']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>461f5e18-7a29-40e5-851e-2ade46542ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0f380e7a-2ac3-451e-a44f-21b867a4dac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Proceso automático instancia (Modificación)</value>
      <webElementGuid>426cbae0-c104-4708-83cd-8e0b3f908f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-content-frame</value>
      <webElementGuid>89e19a71-8cec-49e8-b0f4-431f4a76570b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/AdInsurance/general/Gestion/ProcesoAutomatico/UpdateInstancia/2</value>
      <webElementGuid>796bb965-79e5-4bb3-bb78-75542dc7ab0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This page requires frames in order to show content</value>
      <webElementGuid>155c2256-4750-48ff-8bab-8b609dc59256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalWindow&quot;)/iframe[@class=&quot;k-content-frame&quot;]</value>
      <webElementGuid>9974e652-6473-4e21-bccc-bb6584a5d9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>38c367ae-2ce4-43c3-a5ef-7f6991443a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4e1e392a-7964-42ff-aa58-54ecf7c85d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Proceso automático instancia (Modificación)</value>
      <webElementGuid>72e5dae3-fa99-4f6a-ad4d-f7d65620ddb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-content-frame</value>
      <webElementGuid>d187c8ea-2c70-472d-8a60-53befaa9e1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/AdInsurance/general/Gestion/ProcesoAutomatico/UpdateInstancia/2</value>
      <webElementGuid>552ac3fb-dc1d-40a9-b8e6-e21f475be29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This page requires frames in order to show content</value>
      <webElementGuid>1da0f34c-469f-420e-baea-e4778cc6e58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalWindow&quot;)/iframe[@class=&quot;k-content-frame&quot;]</value>
      <webElementGuid>67f019d7-7ae4-4e8a-a118-68eebf3a1587</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalWindow']/iframe</value>
      <webElementGuid>ab58fa9e-c9cc-4728-838e-bbe738991f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceso automático instancia (Modificación)'])[1]/following::iframe[1]</value>
      <webElementGuid>1b10f202-1030-40ad-882b-981ec110f2aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[2]/following::iframe[1]</value>
      <webElementGuid>346cc6cb-a090-4040-ae53-e1d89d2ecbb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This page requires frames in order to show content']/parent::*</value>
      <webElementGuid>a7ebb060-6bd7-42cc-9ca3-531fde69ffa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5d690ba4-7a57-4a1b-bac4-420a2f7ce5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Proceso automático instancia (Modificación)' and @src = '/AdInsurance/general/Gestion/ProcesoAutomatico/UpdateInstancia/2' and (text() = 'This page requires frames in order to show content' or . = 'This page requires frames in order to show content')]</value>
      <webElementGuid>e9bf248a-0704-44c6-b4e0-a01baac0c20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No se encontraron datos.'])[4]/following::iframe[1]</value>
      <webElementGuid>1a42d854-57cf-4d0e-9a83-161b31967f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'modalWindow', '&quot;', ')/iframe[@class=', '&quot;', 'k-content-frame', '&quot;', ']')])[1]/preceding::iframe[1]</value>
      <webElementGuid>1afeb5af-4ac4-400d-8151-54daba69e235</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
