<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Fecha_fa fa-check</name>
   <tag></tag>
   <elementGuidId>4f73eb6d-00a1-4fc8-9227-43759f619fc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='grdParametroInstanciaPar_2']/table/tbody/tr[8]/td/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-check</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdParametroInstanciaPar_2&quot;)/table[1]/tbody[1]/tr[@class=&quot;k-alt k-grid-edit-row&quot;]/td[@class=&quot;k-command-cell k-command-cell&quot;]/a[@class=&quot;abutton&quot;]/i[@class=&quot;fa fa-check&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grdParametroInstanciaPar_2']/table/tbody/tr[8]/td/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/a/i</value>
   </webElementXpaths>
</WebElementEntity>
