<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_fechaFinNuevoViaje</name>
   <tag></tag>
   <elementGuidId>e2997af4-fc56-499e-8992-d97758e63c43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'FechaFin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9890a694-4afe-4622-a965-0aa764be9cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FechaFin</value>
      <webElementGuid>8bca6e24-c5fd-4234-8f25-cfa7369a19c9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
