<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_montoCustodia</name>
   <tag></tag>
   <elementGuidId>509fae2e-0f11-4f6c-936c-e2dab7d41e3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'MontoCustodia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e9fc1ba-51c8-48c4-bb83-0eb63df5d94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MontoCustodia</value>
      <webElementGuid>ff0d3ff2-7181-4caf-a82a-638acd412de6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
