<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_transitoAereoEditar</name>
   <tag></tag>
   <elementGuidId>2a5eea2f-4d09-44a3-bcfb-dec192a1755c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[@id = 'grdRiesgoTransporte_active_cell']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[2]/div[8]/section/div/div[6]/div/div[2]/div[2]/div[1]/div[2]/div/div[3]/div/table/tbody/tr[1]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6b79d1cd-ebfb-457c-8549-05e5a15fc931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grdRiesgoTransporte_active_cell</value>
      <webElementGuid>94ace8dc-1315-48a2-a2e1-dbebd4cd68f7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
