<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>botonModificarPropuesta</name>
   <tag></tag>
   <elementGuidId>ea50330a-6c64-4e6e-a4e9-33b6def7e481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@style id = 'Modificar']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Modificar&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Modificar</value>
   </webElementProperties>
</WebElementEntity>
