<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_propuestaIncompletaSeleccionada</name>
   <tag></tag>
   <elementGuidId>8f97f426-f573-40d0-835b-c8ff878db793</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id=&quot;cbochk_EstadoCotizacionId_listbox&quot;]/li[13][@aria-selected=&quot;true&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
