<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_propuestaEnEsperaSeleccionada</name>
   <tag></tag>
   <elementGuidId>1213a1a5-6513-4bdc-ab84-8a482b184843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id=&quot;cbochk_EstadoCotizacionId_listbox&quot;]/li[12][@aria-selected=&quot;true&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
