<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_k-switch-handle</name>
   <tag></tag>
   <elementGuidId>b6b338ee-1a00-4dcc-b113-78bf1fbfe004</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divCoaseguroAutomatico']//span[@class=&quot;k-switch-handle&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.k-switch-handle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2e3f442a-e6ed-4a98-b6e2-0dabceaed798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-switch-handle</value>
      <webElementGuid>2ebdb871-7a0a-4b20-92e3-792af2e730b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divCoaseguroAutomatico&quot;)/span[@class=&quot;k-switch k-widget k-switch-on&quot;]/span[@class=&quot;k-switch-container&quot;]/span[@class=&quot;k-switch-handle&quot;]</value>
      <webElementGuid>a340b6f5-de6c-4ca6-a961-f13cb29ab651</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCoaseguroAutomatico']/span/span/span[3]</value>
      <webElementGuid>090745f8-c26b-4f4f-883e-08b4766a43e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[3]</value>
      <webElementGuid>f66008a9-8962-492c-b408-8614174558ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
