<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Riesgo_1_4</name>
   <tag></tag>
   <elementGuidId>c68d0fda-61a2-43cd-ad88-04685f1a38f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='grdRiesgo']/table/tbody/tr[1]/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.editable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4a449e49-eaca-438e-b1ce-16a13e49aa9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Base: 1700000 Tope: 1000000000</value>
      <webElementGuid>ce45c857-9658-4d20-8a2b-01665c79312b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>cd6f7e95-97ba-41d1-92bd-43324faa4552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>8692e140-3b62-49a7-9a79-3b416807bfce</value>
      <webElementGuid>b1b86452-5f43-40b6-bca2-fb9212a1680b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>15035b7c-753a-4351-8c47-aea2b6758a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1.800.000,00</value>
      <webElementGuid>2f77d464-ec9b-4145-934d-b70da90e0099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grdRiesgo&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;editable&quot;]</value>
      <webElementGuid>ae98634c-4816-46f2-a987-4761983022f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grdRiesgo']/table/tbody/tr/td[4]</value>
      <webElementGuid>526f566e-2419-4cec-8a66-76a6fed7510d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DESEMPEÑO DE ACTIVIDAD O PROFESIÓN'])[1]/following::td[1]</value>
      <webElementGuid>3d8d7830-a177-4906-9d94-8d6580cc6bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CDACT'])[1]/following::td[2]</value>
      <webElementGuid>f20e0c7a-203f-455f-a95f-83bd47704d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[4]/preceding::td[4]</value>
      <webElementGuid>b31e6e54-87fc-40c8-8678-97c1832a64b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sí'])[4]/preceding::td[5]</value>
      <webElementGuid>ea607092-aacf-435e-9d4c-dcc555dc7ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td[4]</value>
      <webElementGuid>2544abbe-8ba4-462b-8dc4-809d06ca3855</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
