<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_productorNombre</name>
   <tag></tag>
   <elementGuidId>be11689a-1d4d-4e4f-8aca-a9358f5316d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'Id_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f26d808-2530-4298-b2f3-b964bbd4f161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Id_input</value>
      <webElementGuid>b05368bb-99cc-40ff-9db3-861d14051256</webElementGuid>
   </webElementProperties>
</WebElementEntity>
