<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tipoProductor</name>
   <tag></tag>
   <elementGuidId>56a0ed84-a06e-4026-b17a-bc57f85d3b7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'TipoProductorId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9933de05-28e6-410a-adda-abf5e9821fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TipoProductorId</value>
      <webElementGuid>bf877f37-5093-44d5-95e7-833703c88064</webElementGuid>
   </webElementProperties>
</WebElementEntity>
