<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_editarTeleportacionCuantica</name>
   <tag></tag>
   <elementGuidId>c5791cf9-de5f-4e1e-a55e-ee4531ce4790</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;grdRiesgoTransporte&quot;]/table/tbody/tr[3]/td[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
