<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_porcentajePrimaDeposito</name>
   <tag></tag>
   <elementGuidId>329b7066-439c-443d-99ea-7ec19615215e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'PorcentajePrimaDeposito_DecimalValue']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;divPorcentajePrimaDeposito&quot;]/span/span/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PorcentajePrimaDeposito_DecimalValue</value>
   </webElementProperties>
</WebElementEntity>
