<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_montoEstimado</name>
   <tag></tag>
   <elementGuidId>28085701-0bf9-426b-9625-eadd346092bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'txtMontoEstimado']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;modalBody&quot;]/div/div[1]/div[1]/span/span/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMontoEstimado</value>
   </webElementProperties>
</WebElementEntity>
