<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_celdaMontoEstimadoTransitoAereo</name>
   <tag></tag>
   <elementGuidId>fdc2f0e5-a673-4260-999c-f24f9e320425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;grdRiesgoTransporte&quot;]/table/tbody/tr[1]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
