<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Prosperar</name>
   <tag></tag>
   <elementGuidId>c08e01a9-8db3-4adc-8403-7a4566e02a63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Prosperar']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Prosperar > span.k-link.k-menu-link</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b7be0e04-7f8d-4ce9-af05-64a1db29a472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link k-menu-link</value>
      <webElementGuid>cf952dbc-f5f1-4edd-8c56-280506b7ee51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prosperar</value>
      <webElementGuid>fabd2ca7-e642-4076-bbc2-5dbdf960345f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Prosperar&quot;)/span[@class=&quot;k-link k-menu-link&quot;]</value>
      <webElementGuid>cfb3fa43-f943-42f5-b096-fc1049282b16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Prosperar']/span</value>
      <webElementGuid>4fe96643-58a3-4801-8386-bf36ff507d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Replicar'])[1]/following::span[1]</value>
      <webElementGuid>9b290729-6452-47af-8821-2f4e2d2b0260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modificar'])[1]/following::span[2]</value>
      <webElementGuid>51064014-cc30-4357-80d1-e352c2a72061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultas'])[1]/preceding::span[1]</value>
      <webElementGuid>d47502c1-15b7-4e6e-9e35-8d218f81f2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log de estados'])[1]/preceding::span[3]</value>
      <webElementGuid>006153fa-f9d6-45bd-834b-757e6cc1f81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Prosperar']/parent::*</value>
      <webElementGuid>08b40b3d-96db-4271-9263-d9620db22206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[47]/ul/li[4]/span</value>
      <webElementGuid>6461e209-5ae1-4daa-8e13-669073a532c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Prosperar' or . = 'Prosperar')]</value>
      <webElementGuid>a5d27f0c-d0fb-4c84-8097-9fb0f926fec1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
