<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_desempeñoEditable</name>
   <tag></tag>
   <elementGuidId>06fe4613-7a03-4851-92ee-366fa8b92a29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[@id = 'grdRiesgo_active_cell' and @data-role = 'editable']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id=&quot;grdRiesgo_active_cell&quot; &amp; @data-role=&quot;editable&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grdRiesgo_active_cell</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>editable</value>
   </webElementProperties>
</WebElementEntity>
