<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_grabarInstanciaProcesoAutomatico</name>
   <tag></tag>
   <elementGuidId>a9b22387-4071-439b-bdb6-537d90b55f15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@onclick = 'prevSaveButton();']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;divFooterBar&quot;]/div/div/div[2]/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>prevSaveButton();</value>
   </webElementProperties>
</WebElementEntity>
