<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imagen_emisionProrrogasActivoSi</name>
   <tag></tag>
   <elementGuidId>f74ebaeb-540d-4211-9b11-eeb35c07ef32</elementGuidId>
   <imagePath>Imagenes/Emision/AP/Emision_AP_ProcesosAutomaticos/emsionProrrogasActivoSi.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Imagenes/Emision/AP/Emision_AP_ProcesosAutomaticos/emsionProrrogasActivoSi.png</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
