<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FilterDescripcion_Log</name>
   <tag></tag>
   <elementGuidId>9c3a3ca4-58a7-4f19-bed5-0ff11fea71e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'FilterDescripcion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FilterDescripcion</value>
      <webElementGuid>4fd111c1-5a1b-496a-bc3b-243da56541d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>434b53ab-c37c-488f-b5bd-3e7b4b40d903</webElementGuid>
   </webElementProperties>
</WebElementEntity>
