<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>_ActionGuardarContacto</name>
   <tag></tag>
   <elementGuidId>f953f5f9-e479-46ff-b01e-538389693b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@onclick = 'updateRowContacto()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4cc99771-a400-4b86-86ad-51030d222b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>updateRowContacto()</value>
      <webElementGuid>953616f7-745b-48e0-bc03-54f259e45e68</webElementGuid>
   </webElementProperties>
</WebElementEntity>
