<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>_ActionNuevoDocumento</name>
   <tag></tag>
   <elementGuidId>ac9d9940-5dca-4787-ab19-90148725a608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@onclick = 'showFormDocumento()' and @title = 'Nuevo']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;grdDocumento&quot;]/div[1]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showFormDocumento()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nuevo</value>
   </webElementProperties>
</WebElementEntity>
