<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RelPers_PorcentajeParticipacion1</name>
   <tag></tag>
   <elementGuidId>a0cf199c-9a1e-49e3-9aa0-aa2eb1f72fca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@data-container-for=&quot;PorcentajeParticipacion&quot;]/span/span/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
