<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ramo</name>
   <tag></tag>
   <elementGuidId>e9c3777a-5415-4ec5-ac88-4f11cd46af6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'RamoId_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0d97433-2a08-47ae-9157-8ee1ba08038b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RamoId_input</value>
      <webElementGuid>c96ce79d-d7b1-400a-80e6-937342c558ae</webElementGuid>
   </webElementProperties>
</WebElementEntity>
