<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VigenciaHasta</name>
   <tag></tag>
   <elementGuidId>ca74b3e5-7ab8-4f68-b2f7-f88e096732d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'VigenciaHasta']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e6ebbc9-1ad9-44f6-89f0-56b0a4b3f18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VigenciaHasta</value>
      <webElementGuid>1d929198-4673-4624-8723-5f6e0e6ff286</webElementGuid>
   </webElementProperties>
</WebElementEntity>
