<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Span_Select_PersonasRelacionadas</name>
   <tag></tag>
   <elementGuidId>4b753ddb-aee9-40e5-ab25-acc5c2226383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@aria-controls=&quot;PersonaRelacionada_listbox&quot;]/span/span[@role=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
