<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_numEndosoResults6</name>
   <tag></tag>
   <elementGuidId>e4c9b491-160e-4f4c-a17c-de70ef30d25e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;grdConsultaMovimiento&quot;]/table/tbody/tr[6]/td[@id=&quot;NumeroEndoso&quot;]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
