<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_publico</name>
   <tag></tag>
   <elementGuidId>31185e4a-6b91-4fef-9708-c36392ef5125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[2]/div[8]/section/div/div[5]/div/div[1]/div[2]/div/div/div/div[6]/div[2]/div[2]/div[1]/table/tbody/tr/td[7]/div/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
