<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgExigenciaProductorPrincipal</name>
   <tag></tag>
   <elementGuidId>1b0a3e0b-efc7-4c5a-a1b1-8f1ef164cbe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;grdModalValidaciones&quot;]/table/tbody/tr[2]/td[4]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
