<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_clickCuotificacionAutomatica</name>
   <tag></tag>
   <elementGuidId>6ab19039-4f79-48d4-9d0b-398b46ddb94a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;calculoContent&quot;]/div[2]/div[1]/div/div/span/span/span[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
